// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt1zjsTVQYs_OZLtJSvBQxZpeDnqOqSx4',
    appId: '1:643798867875:web:88541b47762a86e4bb0416',
    messagingSenderId: '643798867875',
    projectId: 'connectwith-60f8a',
    authDomain: 'connectwith-60f8a.firebaseapp.com',
    storageBucket: 'connectwith-60f8a.firebasestorage.app',
    measurementId: 'G-W5D06MS038',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKCwjTBv6gzAf3gMXXu19mf7D0D-rx6Yc',
    appId: '1:643798867875:android:237a2bd56d95a004bb0416',
    messagingSenderId: '643798867875',
    projectId: 'connectwith-60f8a',
    storageBucket: 'connectwith-60f8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV8_H6qHmBV3xExnZeNK2hr942EdA0Mnw',
    appId: '1:643798867875:ios:b876576decc28456bb0416',
    messagingSenderId: '643798867875',
    projectId: 'connectwith-60f8a',
    storageBucket: 'connectwith-60f8a.firebasestorage.app',
    iosBundleId: 'com.example.connectwith',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV8_H6qHmBV3xExnZeNK2hr942EdA0Mnw',
    appId: '1:643798867875:ios:b876576decc28456bb0416',
    messagingSenderId: '643798867875',
    projectId: 'connectwith-60f8a',
    storageBucket: 'connectwith-60f8a.firebasestorage.app',
    iosBundleId: 'com.example.connectwith',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt1zjsTVQYs_OZLtJSvBQxZpeDnqOqSx4',
    appId: '1:643798867875:web:95479ba7f5078d03bb0416',
    messagingSenderId: '643798867875',
    projectId: 'connectwith-60f8a',
    authDomain: 'connectwith-60f8a.firebaseapp.com',
    storageBucket: 'connectwith-60f8a.firebasestorage.app',
    measurementId: 'G-MG12Z9T975',
  );
}
